### PR TITLE
Tiny changes

### PR DESCRIPTION
**Pull request by ronin08**
minor changes

### CODE REVIEW

**Comment by breakdowns** [comment]
If possible check all code then make pr, its already too many pr only for simple things

**Comment by noobzhax** [comment]
fix this [typo ](https://github.com/SlamDevs/slam-mirrorbot/blob/c4035d4ac57ae0ba396123b483ae61d39eb3afd2/bot/modules/leech_settings.py#L31)

**Comment by ronin08** [comment]
> If possible check all code then make pr, its already too many pr only for simple things

> If possible check all code then make pr, its already too many pr only for simple things

I can't look for code errors , you guys are best at it .
I can write good explanations , fix typo , make things look clean . 

tell me where can I look to make such changes .

**Comment by ronin08** [comment]
> fix this [typo ](https://github.com/SlamDevs/slam-mirrorbot/blob/c4035d4ac57ae0ba396123b483ae61d39eb3afd2/bot/modules/leech_settings.py#L31)

eagle eye ... 
look for other typos ..

**Comment by ronin08** [comment]
@breakdowns the wiki contains few typos but I don't have permission to edit it

**Comment by breakdowns** [comment]
> @breakdowns the wiki contains few typos but I don't have permission to edit it

Idk how to give access to wili, you can join support group, then i will send wiki file

**Comment by ronin08** [comment]
It's simple , follow this https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

have taken a break from telegram :)

**Comment by breakdowns** [comment]
> @breakdowns It's simple , follow this https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis
> 
> have taken a break from telegram :)

Try now

**Comment by ronin08** [comment]
> > @breakdowns It's simple , follow this https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis
> > have taken a break from telegram :)
> 
> Try now

fine now .

**Comment by breakdowns** [comment]
> > > @breakdowns It's simple , follow this https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis
> > > have taken a break from telegram :)
> > 
> > 
> > Try now
> 
> fine now .

Then you need change wiki link in readme also

**Pull request merged**
