### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ronin08**
-updated guide for filling MULTI_SEARCH_URL config
-fixed lot of typos
-added credit for service account script .

### CODE REVIEW

**Comment by breakdowns** [comment]
@ronin08 https://t.me/SlamBugReport/20502

**Comment by ronin08** [comment]
> @ronin08 https://t.me/SlamBugReport/20502

Done ! Check now

**Comment by breakdowns** [comment]
Still has some typo in MULTI_SEARCH_URL, but np i already push it https://github.com/SlamDevs/slam-mirrorbot/commit/06553430ba17d9752a80cf76e69051bb9f391aef

**Comment by ronin08** [comment]
> Still has some typo in MULTI_SEARCH_URL, but np i already push it [0655343](https://github.com/SlamDevs/slam-mirrorbot/commit/06553430ba17d9752a80cf76e69051bb9f391aef)

you could have told me . There isn't much difference you have made 😅

**Comment by breakdowns** [comment]
@ronin08 Can you join in this group please @SlamBugReport

**Comment by ronin08** [comment]
@breakdowns why not 😊

**Pull request closed without merging**
