### PR TITLE
bot: Change deploy method

### PR DESCRIPTION
**Pull request by gudmeong**
- change deploy method to heroku container registry
- for now, we no need HEROKU_EMAIL in github secrets
- update credits

Signed-off-by: GudMeong <avada758@gmail.com>

### CODE REVIEW

**Comment by anasty17** [comment]
@gudmeong Why we need to change deploy method?

**Comment by gudmeong** [comment]
> @gudmeong Why we need to change deploy method?

btw this is optional, up to you wanna merge this commit or not. but on my own forked repo i change that. just wanna merge to upstream repo  :)

**Comment by anasty17** [comment]
@gudmeong How your commit can't be optional !
So no purpose from this commit !

**Comment by breakdowns** [comment]
> * change deploy method to heroku container registry
> * for now, we no need HEROKU_EMAIL in github secrets
> * update credits
> 
> Signed-off-by: GudMeong [avada758@gmail.com](mailto:avada758@gmail.com)

Thanks :) will try later, will merge if doesn't have issue, i think is much easy, coz i see someone in support can't understand HEROKU_EMAIL

**Comment by anasty17** [comment]
@breakdowns How he can't understand heroku email and he made the heroku account by email wth

**Pull request closed without merging**
